In [1]:
import pandas as pd

In [4]:
pd.read_table('/Users/nickpourazima/GitHub/he-sm/TestOutput/Nick/Nick H2b4 Wed Apr 18 15:01:13 2018.tsv')

                                                 Timestamp    Haptic Elapsed Time    Haptic Onset  Tap Elapsed Time    Tap Onset
0     --------------------------  ------------  ----...
1     2018-04-18 14:53:21.569046   0                ...
2     2018-04-18 14:53:22.016753   0.0105021        ...
3     2018-04-18 14:53:22.448442   0.45821          ...
4     2018-04-18 14:53:22.896049   0.889899         ...
5     2018-04-18 14:53:23.343624   1.33751          ...
6     2018-04-18 14:53:23.791362   1.78508          ...
7     2018-04-18 14:53:24.223128   2.23282          ...
8     2018-04-18 14:53:24.670663   2.66458          ...
9     2018-04-18 14:53:25.118356   3.11212          ...
10    2018-04-18 14:53:25.565972   3.55981          ...
11    2018-04-18 14:53:25.997784   4.00742          ...
12    2018-04-18 14:53:26.445484   4.43924          ...
13    2018-04-18 14:53:26.893222   4.88694          ...
14    2018-04-18 14:53:27.340871   5.33468          ...
15    2018-04-18 14:53:27.788530   5.78233          ...
16    2018-04-18 14:53:28.220249   6.22999          ...
17    2018-04-18 14:53:28.667989   6.66171          ...
18    2018-04-18 14:53:29.115642   7.10945          ...
19    2018-04-18 14:53:29.563386   7.5571           ...
20    2018-04-18 14:53:29.995130   8.00484          ...
21    2018-04-18 14:53:30.442674   8.43659          ...
22    2018-04-18 14:53:30.890352   8.88413          ...
23    2018-04-18 14:53:31.337972   9.33181          ...
24    2018-04-18 14:53:31.769756   9.77943          ...
25    2018-04-18 14:53:32.217494  10.2112           ...
26    2018-04-18 14:53:32.665172  10.659            ...
27    2018-04-18 14:53:33.112937  11.1066           ...
28    2018-04-18 14:53:33.544653  11.5544           ...
29    2018-04-18 14:53:33.992234  11.9861           ...
...                                                 ...
1338  2018-04-18 15:01:03.577495                    ...
1339  2018-04-18 15:01:03.872273                    ...
1340  2018-04-18 15:01:04.224417                    ...
1341  2018-04-18 15:01:04.580574                    ...
1342  2018-04-18 15:01:04.895802                    ...
1343  2018-04-18 15:01:05.231475                    ...
1344  2018-04-18 15:01:05.538577                    ...
1345  2018-04-18 15:01:05.870168                    ...
1346  2018-04-18 15:01:06.193607                    ...
1347  2018-04-18 15:01:06.521059                    ...
1348  2018-04-18 15:01:06.824111                    ...
1349  2018-04-18 15:01:07.155727                    ...
1350  2018-04-18 15:01:07.442390                    ...
1351  2018-04-18 15:01:07.741163                    ...
1352  2018-04-18 15:01:08.060293                    ...
1353  2018-04-18 15:01:08.359461                    ...
1354  2018-04-18 15:01:08.653970                    ...
1355  2018-04-18 15:01:08.969523                    ...
1356  2018-04-18 15:01:09.296916                    ...
1357  2018-04-18 15:01:09.583579                    ...
1358  2018-04-18 15:01:09.890548                    ...
1359  2018-04-18 15:01:10.201686                    ...
1360  2018-04-18 15:01:10.537410                    ...
1361  2018-04-18 15:01:10.848571                    ...
1362  2018-04-18 15:01:11.147245                    ...
1363  2018-04-18 15:01:11.438110                    ...
1364  2018-04-18 15:01:11.777860                    ...
1365  2018-04-18 15:01:12.101188                    ...
1366  2018-04-18 15:01:12.416530                    ...
1367  2018-04-18 15:01:12.752274                    ...

[1368 rows x 1 columns]